version: '3.5'
services:
  timescaledb:
    image: timescale/timescaledb:1.6.0-pg11
    container_name: timescaledb
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/zabbix/postgresql/data:/var/lib/postgresql/data:rw
    user: root
    stop_grace_period: 1m
    environment:
     - POSTGRES_USER=zabbix
     - POSTGRES_PASSWORD=abc123
     - TS_TUNE_MEMORY=7GB
     - TS_TUNE_NUM_CPUS=7
    logging:
      driver: "json-file"
      options:
        max-size: "128M"